### PR TITLE
Use external symlink script

### PR DESCRIPTION
**Pull request by Jameskmonger**
This uses the [modulink](https://www.npmjs.com/package/modulink) library which allows us to create a symlink for development purposes rather than having to create/maintain a script to do it by ourselves.

### CODE REVIEW

**Comment by Jameskmonger** [comment]
@perry-mitchell Not sure why there are so many changes being shown in `package.json`. The only change I made was adding `"modulink": "^1.1.0"` to `devDependencies`, and this script:

    "install": "npm run symlink",
    "symlink": "node node_modules/modulink/modulink --name=__buttercup --target=source"

**Comment by Jameskmonger** [comment]
@perry-mitchell I also removed the dependency on `fs-symlink` as it's no longer necessary.

**Comment by perry-mitchell** [comment]
Hi @Jameskmonger - Not sure why we need this though. I applaud you in your efforts in making a module for this - it was definitely needed - but I don't see a benefit in including your module to do what our tiny script was doing.

In this regard, I feel having less dependencies is a plus.

**Comment by Jameskmonger** [comment]
No problem @perry-mitchell! I used the link script a couple of times in personal projects but found it a bit easier to just `npm install` a module, so I made `modulink`. I understand if you want to keep dependencies to a minimum, though :smile:

**Pull request closed without merging**
