### PR TITLE
Archive attributes

### LINKED ISSUE #100: Attributes for Archives
Give archives attributes.

### PR DESCRIPTION
**Pull request by perry-mitchell**
Fixes #100 

Changes:

- Change commands to ES6 classes
- Change command file names to their class names
- Added SAA + DAA commands (set-archive-attribute and delete-archive-attribute)
- Modified Descriptor to include archive attributes
- Updated tests and added new ones for the new commands
- Unwrapped some modules from the `(function(module) { /* ... */ })(module)` pattern

### CODE REVIEW

**Comment by perry-mitchell** [comment]
@sallar @Jameskmonger Would love a quick review if you gents get any time. No immediate rush on this one 😄

**Comment by sallar** [comment]
49 files 😱

**Comment by perry-mitchell** [comment]
@sallar The changes are quite basic, even though it looks like a lot. I'll update with a summary of changes.

**Comment by perry-mitchell** [comment]
The tests pass, so I'd like to merge this today @sallar @Jameskmonger - It doesn't really need a review imho, but I thought it good practice to ask anyhow 😄 

This is needed for the refactor in the GUI.

**Comment by Jameskmonger** [comment]
Sorry @perry-mitchell I was away!

**Comment by perry-mitchell** [comment]
@Jameskmonger No problem! There's a lot more cool stuff on its way!

**Pull request merged**
