### PR TITLE
Fix #70: Remove symlink dependency for source files

### LINKED ISSUE #70: Cannot find module '__buttercup/classes/Archive.js'
error message

@himynameisdave can you provide some more info on this?

### PR DESCRIPTION
**Pull request by Jameskmonger**
This uses relative references in the source files rather than relying on the symlink.

### CODE REVIEW

**Comment by perry-mitchell** [comment]
As stated earlier, having the hard-coded paths is a must for the downstream projects. There is nothing wrong, imo, with having "full" paths in each file. It works like namespacing, and the verbosity is much nicer than relative paths too.

**Comment by Jameskmonger** [comment]
That's fine @perry-mitchell - this could potentially fix the symlinking issue, though. (#70)

**Comment by perry-mitchell** [comment]
@Jameskmonger I'm not wholly convinced there is a massive issue, as symlinks are quite trivial (even on Windows it seems). What doesn't seem trivial is how npm manages it's installation procedures - we had some quirks in buttercup-core-web with the symlink some time ago, but I don't completely recall exactly where all the issues were.

Regardless of this learning process, we've had to stick to using the symlinks to ensure that not only our paths are readable, but they work properly when run through browserify (a requirement for the Chrome extension). If they are proven to be a massive problem going forward, we'll definitely reassess their usefulness.

**Comment by perry-mitchell** [comment]
This is sorted in #73 where we've removed symlinks completely.

**Pull request closed without merging**
